"""empty message

Revision ID: 8e6683a8853c
Revises: a5cffa318ac2
Create Date: 2026-05-27 08:15:06.724297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6683a8853c'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, Foreign_Key='user.id'),
    sa.Column('people_id', sa.Integer(), nullable=False, Foreign_Key='people.id'),
    sa.Column('vehicle_id', sa.Integer(), nullable=False, Foreign_Key='vehicle.id'),
    sa.Column('planet_id', sa.Integer(), nullable=False, Foreign_Key='planet.id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('birth_year', sa.String(length=16), nullable=True),
    sa.Column('eye_color', sa.String(length=16), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('hair_color', sa.String(length=16), nullable=True),
    sa.Column('height', sa.String(length=16), nullable=True),
    sa.Column('mass', sa.String(length=16), nullable=True),
    sa.Column('skin_color', sa.String(length=16), nullable=True),
    sa.Column('homeworld', sa.String(length=128), nullable=True),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('edited', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('gravity', sa.String(length=16), nullable=True),
    sa.Column('population', sa.String(length=16), nullable=True),
    sa.Column('climate', sa.String(length=128), nullable=True),
    sa.Column('terrain', sa.String(length=128), nullable=True),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('edited', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('vehicle_class', sa.String(length=128), nullable=False),
    sa.Column('manufacturer', sa.String(length=128), nullable=False),
    sa.Column('speed', sa.String(length=16), nullable=True),
    sa.Column('weight', sa.String(length=16), nullable=True),
    sa.Column('length', sa.String(length=16), nullable=True),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('edited', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('created', sa.Integer(), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=16),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=128),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('created')
        batch_op.drop_column('username')
        batch_op.drop_column('full_name')

    op.drop_table('vehicle')
    op.drop_table('planet')
    op.drop_table('people')
    op.drop_table('favorite')
    # ### end Alembic commands ###
